# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:27:16+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer
from fastapi import Header, Path, Query

from models import (
    AccountTypeEnum,
    CreateWebhookRequest,
    CreateWebhookResponse,
    ErrorResponse,
    GetAccountResponse,
    GetCategoryResponse,
    GetTransactionResponse,
    GetWebhookResponse,
    ListAccountsResponse,
    ListCategoriesResponse,
    ListTagsResponse,
    ListTransactionsResponse,
    ListWebhookDeliveryLogsResponse,
    ListWebhooksResponse,
    OwnershipTypeEnum,
    PingResponse,
    TransactionStatusEnum,
    UpdateTransactionCategoryRequest,
    UpdateTransactionTagsRequest,
    WebhookEventCallback,
)

app = MCPProxy(
    contact={
        'name': 'API Specification and Support',
        'url': 'https://github.com/up-banking/api',
    },
    description='The Up API gives you programmatic access to your balances and\ntransaction data. You can request past transactions or set up\nwebhooks to receive real-time events when new transactions hit your\naccount. It’s new, it’s exciting and it’s just the beginning.\n',
    title='Up API',
    version='v1',
    servers=[{'url': 'https://api.up.com.au/api/v1'}],
)


@app.get(
    '/accounts',
    description=""" Retrieve a paginated list of all accounts for the currently
authenticated user. The returned list is paginated and can be scrolled
by following the `prev` and `next` links where present.
 """,
    tags=['account_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_accounts(
    page_size_: Optional[int] = Query(None, alias='page[size]'),
    filter_account_type_: Optional[AccountTypeEnum] = Query(
        None, alias='filter[accountType]'
    ),
    filter_ownership_type_: Optional[OwnershipTypeEnum] = Query(
        None, alias='filter[ownershipType]'
    ),
):
    """
    List accounts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/accounts/{accountId}/transactions',
    description=""" Retrieve a list of all transactions for a specific account. The returned
list is [paginated](#pagination) and can be scrolled by following the
`next` and `prev` links where present. To narrow the results to a
specific date range pass one or both of `filter[since]` and
`filter[until]` in the query string. These filter parameters
**should not** be used for pagination. Results are ordered newest first
to oldest last.
 """,
    tags=[
        'account_handling',
        'transaction_handling',
        'category_handling',
        'tag_handling',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_accounts__account_id_transactions(
    account_id: str = Path(..., alias='accountId'),
    page_size_: Optional[int] = Query(None, alias='page[size]'),
    filter_status_: Optional[TransactionStatusEnum] = Query(
        None, alias='filter[status]'
    ),
    filter_since_: Optional[datetime] = Query(None, alias='filter[since]'),
    filter_until_: Optional[datetime] = Query(None, alias='filter[until]'),
    filter_category_: Optional[str] = Query(None, alias='filter[category]'),
    filter_tag_: Optional[str] = Query(None, alias='filter[tag]'),
):
    """
    List transactions by account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/accounts/{id}',
    description=""" Retrieve a specific account by providing its unique identifier.
 """,
    tags=['account_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_accounts__id(id: str):
    """
    Retrieve account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/categories',
    description=""" Retrieve a list of all categories and their ancestry. The returned list
is not paginated.
 """,
    tags=['category_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_categories(filter_parent_: Optional[str] = Query(None, alias='filter[parent]')):
    """
    List categories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/categories/{id}',
    description=""" Retrieve a specific category by providing its unique identifier.
 """,
    tags=['category_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_categories__id(id: str):
    """
    Retrieve category
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/tags',
    description=""" Retrieve a list of all tags currently in use. The returned list is
[paginated](#pagination) and can be scrolled by following the `next`
and `prev` links where present. Results are ordered lexicographically.
The `transactions` relationship for each tag exposes a link
to get the transactions with the given tag.
 """,
    tags=['tag_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_tags(page_size_: Optional[int] = Query(None, alias='page[size]')):
    """
    List tags
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/transactions',
    description=""" Retrieve a list of all transactions across all accounts for the currently
authenticated user. The returned list is [paginated](#pagination) and can
be scrolled by following the `next` and `prev` links where present. To
narrow the results to a specific date range pass one or both of
`filter[since]` and `filter[until]` in the query string. These filter
parameters **should not** be used for pagination. Results are ordered
newest first to oldest last.
 """,
    tags=['transaction_handling', 'tag_handling', 'category_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_transactions(
    page_size_: Optional[int] = Query(None, alias='page[size]'),
    filter_status_: Optional[TransactionStatusEnum] = Query(
        None, alias='filter[status]'
    ),
    filter_since_: Optional[datetime] = Query(None, alias='filter[since]'),
    filter_until_: Optional[datetime] = Query(None, alias='filter[until]'),
    filter_category_: Optional[str] = Query(None, alias='filter[category]'),
    filter_tag_: Optional[str] = Query(None, alias='filter[tag]'),
):
    """
    List transactions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/transactions/{id}',
    description=""" Retrieve a specific transaction by providing its unique identifier.
 """,
    tags=['transaction_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_transactions__id(id: str):
    """
    Retrieve transaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/transactions/{transactionId}/relationships/category',
    description=""" Updates the category associated with a transaction. Only transactions
for which `isCategorizable` is set to true support this operation. The
`id` is taken from the list exposed on `/categories` and cannot be one of
the top-level (parent) categories. To de-categorize a transaction, set
the entire `data` key to `null`. An HTTP `204` is returned on success.
The associated category, along with its request URL is also exposed via
the `category` relationship on the transaction resource returned from
`/transactions/{id}`.
 """,
    tags=['transaction_handling', 'category_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def patch_transactions__transaction_id_relationships_category(
    transaction_id: str = Path(..., alias='transactionId'),
    body: UpdateTransactionCategoryRequest = None,
):
    """
    Categorize transaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/transactions/{transactionId}/relationships/tags',
    description=""" Disassociates one or more tags from a specific transaction. Tags that are
not associated are silently ignored. An HTTP `204` is returned on
success. The associated tags, along with this request URL, are also
exposed via the `tags` relationship on the transaction resource returned
from `/transactions/{id}`.
 """,
    tags=['transaction_handling', 'tag_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_transactions__transaction_id_relationships_tags(
    transaction_id: str = Path(..., alias='transactionId'),
    body: UpdateTransactionTagsRequest = None,
):
    """
    Remove tags from transaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/transactions/{transactionId}/relationships/tags',
    description=""" Associates one or more tags with a specific transaction. No more than 6
tags may be present on any single transaction. Duplicate tags are
silently ignored. An HTTP `204` is returned on success. The associated
tags, along with this request URL, are also exposed via the `tags`
relationship on the transaction resource returned from
`/transactions/{id}`.
 """,
    tags=['transaction_handling', 'tag_handling'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_transactions__transaction_id_relationships_tags(
    transaction_id: str = Path(..., alias='transactionId'),
    body: UpdateTransactionTagsRequest = None,
):
    """
    Add tags to transaction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/util/ping',
    description=""" Make a basic ping request to the API. This is useful to verify that
authentication is functioning correctly. On authentication success an
HTTP `200` status is returned. On failure an HTTP `401` error response
is returned.
 """,
    tags=['service_utilities'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_util_ping():
    """
    Ping
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks',
    description=""" Retrieve a list of configured webhooks. The returned list is
[paginated](#pagination) and can be scrolled by following the `next`
and `prev` links where present. Results are ordered oldest first to
newest last.
 """,
    tags=['webhook_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_webhooks(page_size_: Optional[int] = Query(None, alias='page[size]')):
    """
    List webhooks
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/webhooks',
    description=""" Create a new webhook with a given URL. The URL will receive webhook
events as JSON-encoded `POST` requests. The URL must respond with a HTTP
`200` status on success.

There is currently a limit of 10 webhooks at any given time. Once this
limit is reached, existing webhooks will need to be deleted before new
webhooks can be created.

Event delivery is retried with exponential backoff if the URL is
unreachable or it does not respond with a `200` status. The response
includes a `secretKey` attribute, which is used to sign requests sent to
the webhook URL. It will not be returned from any other endpoints within
the Up API. If the `secretKey` is lost, simply create a new webhook with
the same URL, capture its `secretKey` and then delete the original
webhook. See [Handling webhook events](#callback_post_webhookURL) for
details on how to process webhook events.

It is probably a good idea to test the webhook by
[sending it a `PING` event](#post_webhooks_webhookId_ping) after creating
it.
 """,
    tags=['webhook_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_webhooks(body: CreateWebhookRequest = None):
    """
    Create webhook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/webhooks/{id}',
    description=""" Delete a specific webhook by providing its unique identifier. Once
deleted, webhook events will no longer be sent to the configured URL.
 """,
    tags=['webhook_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_webhooks__id(id: str):
    """
    Delete webhook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks/{id}',
    description=""" Retrieve a specific webhook by providing its unique identifier.
 """,
    tags=['webhook_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_webhooks__id(id: str):
    """
    Retrieve webhook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks/{webhookId}/logs',
    description=""" Retrieve a list of delivery logs for a webhook by providing its unique
identifier. This is useful for analysis and debugging purposes. The
returned list is [paginated](#pagination) and can be scrolled by
following the `next` and `prev` links where present. Results are ordered
newest first to oldest last. Logs may be automatically purged after a
period of time.
 """,
    tags=['webhook_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_webhooks__webhook_id_logs(
    webhook_id: str = Path(..., alias='webhookId'),
    page_size_: Optional[int] = Query(None, alias='page[size]'),
):
    """
    List webhook logs
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/webhooks/{webhookId}/ping',
    description=""" Send a `PING` event to a webhook by providing its unique identifier.
This is useful for testing and debugging purposes. The event is delivered
asynchronously and its data is returned in the response to this request.
 """,
    tags=['webhook_operations', 'service_utilities'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def post_webhooks__webhook_id_ping(webhook_id: str = Path(..., alias='webhookId')):
    """
    Ping webhook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
