# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:27:16+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, Field


class Links(BaseModel):
    self: str = Field(
        ..., description='The canonical link to this resource within the API.\n'
    )


class Links1(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class Transactions(BaseModel):
    links: Optional[Links1] = None


class Relationships(BaseModel):
    transactions: Transactions


class AccountTypeEnum(Enum):
    SAVER = 'SAVER'
    TRANSACTIONAL = 'TRANSACTIONAL'


class CategoryInputResourceIdentifier(BaseModel):
    id: str = Field(
        ...,
        description='The unique identifier of the category, as returned by the `/categories`\nendpoint.\n',
    )
    type: str = Field(..., description='The type of this resource: `categories`')


class Attributes1(BaseModel):
    name: str = Field(
        ..., description='The name of this category as seen in the Up application.\n'
    )


class Links2(BaseModel):
    self: str = Field(
        ..., description='The canonical link to this resource within the API.\n'
    )


class Datum(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `categories`')


class Links3(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class Children(BaseModel):
    data: List[Datum]
    links: Optional[Links3] = None


class Data(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `categories`')


class Parent(BaseModel):
    data: Data
    links: Optional[Links3] = None


class Relationships1(BaseModel):
    children: Children
    parent: Parent


class CategoryResource(BaseModel):
    attributes: Attributes1
    id: str = Field(
        ...,
        description='The unique identifier for this category. This is a human-readable but\nURL-safe value.\n',
    )
    links: Optional[Links2] = None
    relationships: Relationships1
    type: str = Field(..., description='The type of this resource: `categories`')


class Source(BaseModel):
    parameter: Optional[str] = Field(
        None,
        description='If this error relates to a query parameter, the name of the\nparameter.\n',
    )
    pointer: Optional[str] = Field(
        None,
        description='If this error relates to an attribute in the request body, a\nrfc-6901 JSON pointer to the attribute.\n',
    )


class ErrorObject(BaseModel):
    detail: str = Field(
        ...,
        description='A detailed description of this error. This should be considered unique\nto individual occurrences of an error and subject to change. It is\nuseful for debugging purposes.\n',
    )
    source: Optional[Source] = Field(
        None,
        description='If applicable, location in the request that this error relates to. This\nmay be a parameter in the query string, or a an attribute in the\nrequest body.\n',
    )
    status: str = Field(
        ...,
        description='The HTTP status code associated with this error. This can also be\nobtained from the response headers. The status indicates the broad type\nof error according to HTTP semantics.\n',
    )
    title: str = Field(
        ...,
        description='A short description of this error. This should be stable across\nmultiple occurrences of this type of error and typically expands on the\nreason for the status code.\n',
    )


class ErrorResponse(BaseModel):
    errors: List[ErrorObject] = Field(
        ..., description='The list of errors returned in this response.\n'
    )


class GetCategoryResponse(BaseModel):
    data: CategoryResource = Field(
        ..., description='The category returned in this response.\n'
    )


class Links5(BaseModel):
    next: str = Field(
        ...,
        description='The link to the next page in the results. If this value is `null`\nthere is no next page.\n',
    )
    prev: str = Field(
        ...,
        description='The link to the previous page in the results. If this value is `null`\nthere is no previous page.\n',
    )


class ListCategoriesResponse(BaseModel):
    data: List[CategoryResource] = Field(
        ..., description='The list of categories returned in this response.\n'
    )


class MoneyObject(BaseModel):
    currencyCode: str = Field(..., description='The ISO 4217 currency code.\n')
    value: str = Field(
        ...,
        description='The amount of money, formatted as a string in the relevant currency.\nFor example, for an Australian dollar value of $10.56, this field will\nbe `"10.56"`. The currency symbol is not included in the string.\n',
    )
    valueInBaseUnits: int = Field(
        ...,
        description='The amount of money in the smallest denomination for the currency, as a\n64-bit integer.  For example, for an Australian dollar value of $10.56,\nthis field will be `1056`.\n',
    )


class OwnershipTypeEnum(Enum):
    INDIVIDUAL = 'INDIVIDUAL'
    JOINT = 'JOINT'


class Meta(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the authenticated customer.\n'
    )
    statusEmoji: str = Field(
        ..., description='A cute emoji that represents the response status.\n'
    )


class PingResponse(BaseModel):
    meta: Meta


class RoundUpObject(BaseModel):
    amount: MoneyObject = Field(
        ...,
        description='The total amount of this Round Up, including any boosts, represented as\na negative value.\n',
    )
    boostPortion: MoneyObject = Field(
        ...,
        description='The portion of the Round Up `amount` owing to boosted Round Ups,\nrepresented as a negative value. If no boost was added to the Round Up\nthis field will be `null`.\n',
    )


class TagInputResourceIdentifier(BaseModel):
    id: str = Field(
        ...,
        description='The label of the tag, which also acts as the tag’s unique identifier.\n',
    )
    type: str = Field(..., description='The type of this resource: `tags`')


class Links10(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class Transactions1(BaseModel):
    links: Optional[Links10] = None


class Relationships2(BaseModel):
    transactions: Transactions1


class TagResource(BaseModel):
    id: str = Field(
        ...,
        description='The label of the tag, which also acts as the tag’s unique identifier.\n',
    )
    relationships: Relationships2
    type: str = Field(..., description='The type of this resource: `tags`')


class Links11(BaseModel):
    self: str = Field(
        ..., description='The canonical link to this resource within the API.\n'
    )


class Data1(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `accounts`')


class Links12(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class Account(BaseModel):
    data: Data1
    links: Optional[Links12] = None


class Data2(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `categories`')


class Links13(BaseModel):
    related: Optional[str] = Field(
        None,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )
    self: str = Field(
        ...,
        description='The link to retrieve or modify linkage between this resources and the\nrelated resource(s) in this relationship.\n',
    )


class Category(BaseModel):
    data: Data2
    links: Optional[Links13] = None


class Links14(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class ParentCategory(BaseModel):
    data: Data2
    links: Optional[Links14] = None


class Datum1(BaseModel):
    id: str = Field(
        ...,
        description='The label of the tag, which also acts as the tag’s unique identifier.\n',
    )
    type: str = Field(..., description='The type of this resource: `tags`')


class Links15(BaseModel):
    self: str = Field(
        ...,
        description='The link to retrieve or modify linkage between this resources and the\nrelated resource(s) in this relationship.\n',
    )


class Tags(BaseModel):
    data: List[Datum1]
    links: Optional[Links15] = None


class Data4(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `accounts`')


class Links16(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class TransferAccount(BaseModel):
    data: Data4
    links: Optional[Links16] = None


class Relationships3(BaseModel):
    account: Account
    category: Category
    parentCategory: ParentCategory
    tags: Tags
    transferAccount: TransferAccount = Field(
        ...,
        description='If this transaction is a transfer between accounts, this relationship\nwill contain the account the transaction went to/came from. The\n`amount` field can be used to determine the direction of the transfer.\n',
    )


class TransactionStatusEnum(Enum):
    HELD = 'HELD'
    SETTLED = 'SETTLED'


class UpdateTransactionCategoryRequest(BaseModel):
    data: CategoryInputResourceIdentifier = Field(
        ...,
        description='The category to set on the transaction. Set this entire key to `null`\nde-categorize a transaction.\n',
    )


class UpdateTransactionTagsRequest(BaseModel):
    data: List[TagInputResourceIdentifier] = Field(
        ..., description='The tags to add to or remove from the transaction.\n'
    )


class Request(BaseModel):
    body: str = Field(
        ..., description='The payload that was sent in the request body.\n'
    )


class Response(BaseModel):
    body: str = Field(
        ..., description='The payload that was received in the response body.\n'
    )
    statusCode: int = Field(
        ..., description='The HTTP status code received in the response.\n'
    )


class Data5(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `webhook-events`')


class WebhookEvent(BaseModel):
    data: Data5


class Relationships4(BaseModel):
    webhookEvent: WebhookEvent


class WebhookDeliveryStatusEnum(Enum):
    DELIVERED = 'DELIVERED'
    UNDELIVERABLE = 'UNDELIVERABLE'
    BAD_RESPONSE_CODE = 'BAD_RESPONSE_CODE'


class Data6(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `transactions`')


class Transaction(BaseModel):
    data: Data6
    links: Optional[Links16] = None


class Data7(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the resource within its type.\n'
    )
    type: str = Field(..., description='The type of this resource: `webhooks`')


class Webhook(BaseModel):
    data: Data7
    links: Optional[Links16] = None


class Relationships5(BaseModel):
    transaction: Optional[Transaction] = None
    webhook: Webhook


class WebhookEventTypeEnum(Enum):
    TRANSACTION_CREATED = 'TRANSACTION_CREATED'
    TRANSACTION_SETTLED = 'TRANSACTION_SETTLED'
    TRANSACTION_DELETED = 'TRANSACTION_DELETED'
    PING = 'PING'


class Attributes5(BaseModel):
    description: Optional[str] = Field(
        None,
        description='An optional description for this webhook, up to 64 characters in\nlength.\n',
    )
    url: AnyUrl = Field(
        ...,
        description='The URL that this webhook should post events to. This must be a valid\nHTTP or HTTPS URL that does not exceed 300 characters in length.\n',
    )


class WebhookInputResource(BaseModel):
    attributes: Attributes5


class Attributes6(BaseModel):
    createdAt: datetime = Field(
        ..., description='The date-time at which this webhook was created.\n'
    )
    description: str = Field(
        ...,
        description='An optional description that was provided at the time the webhook was\ncreated.\n',
    )
    secretKey: Optional[str] = Field(
        None,
        description='A shared secret key used to sign all webhook events sent to the\nconfigured webhook URL. This field is returned only once, upon the\ninitial creation of the webhook. If lost, create a new webhook and\ndelete this webhook.\n\nThe webhook URL receives a request with a\n`X-Up-Authenticity-Signature` header, which is the SHA-256 HMAC of\nthe entire raw request body signed using this `secretKey`. It is\nadvised to compute and check this signature to verify the\nauthenticity of requests sent to the webhook URL. See\n[Handling webhook events](#callback_post_webhookURL) for full\ndetails.\n',
    )
    url: str = Field(
        ...,
        description='The URL that this webhook is configured to `POST` events to.\n',
    )


class Links19(BaseModel):
    self: str = Field(
        ..., description='The canonical link to this resource within the API.\n'
    )


class Links20(BaseModel):
    related: str = Field(
        ...,
        description='The link to retrieve the related resource(s) in this relationship.\n',
    )


class Logs(BaseModel):
    links: Optional[Links20] = None


class Relationships6(BaseModel):
    logs: Logs


class WebhookResource(BaseModel):
    attributes: Attributes6
    id: str = Field(..., description='The unique identifier for this webhook.\n')
    links: Optional[Links19] = None
    relationships: Relationships6
    type: str = Field(..., description='The type of this resource: `webhooks`')


class Attributes(BaseModel):
    accountType: AccountTypeEnum = Field(
        ..., description='The bank account type of this account.\n'
    )
    balance: MoneyObject = Field(
        ...,
        description='The available balance of the account, taking into account any amounts\nthat are currently on hold.\n',
    )
    createdAt: datetime = Field(
        ..., description='The date-time at which this account was first opened.\n'
    )
    displayName: str = Field(
        ..., description='The name associated with the account in the Up application.\n'
    )
    ownershipType: OwnershipTypeEnum = Field(
        ..., description='The ownership structure for this account.\n'
    )


class AccountResource(BaseModel):
    attributes: Attributes
    id: str = Field(..., description='The unique identifier for this account.\n')
    links: Optional[Links] = None
    relationships: Relationships
    type: str = Field(..., description='The type of this resource: `accounts`')


class CashbackObject(BaseModel):
    amount: MoneyObject = Field(
        ...,
        description='The total amount of cashback paid, represented as a positive value.\n',
    )
    description: str = Field(
        ..., description='A brief description of why this cashback was paid.\n'
    )


class CreateWebhookRequest(BaseModel):
    data: WebhookInputResource = Field(
        ..., description='The webhook resource to create.\n'
    )


class CreateWebhookResponse(BaseModel):
    data: WebhookResource = Field(..., description='The webhook that was created.\n')


class GetAccountResponse(BaseModel):
    data: AccountResource = Field(
        ..., description='The account returned in this response.\n'
    )


class GetWebhookResponse(BaseModel):
    data: WebhookResource = Field(
        ..., description='The webhook returned in this response.\n'
    )


class HoldInfoObject(BaseModel):
    amount: MoneyObject = Field(
        ...,
        description='The amount of this transaction while in the `HELD` status, in\nAustralian dollars.\n',
    )
    foreignAmount: MoneyObject = Field(
        ...,
        description='The foreign currency amount of this transaction while in the `HELD`\nstatus. This field will be `null` for domestic transactions. The amount\nwas converted to the AUD amount reflected in the `amount` field.\n',
    )


class ListAccountsResponse(BaseModel):
    data: List[AccountResource] = Field(
        ..., description='The list of accounts returned in this response.\n'
    )
    links: Links5


class ListTagsResponse(BaseModel):
    data: List[TagResource] = Field(
        ..., description='The list of tags returned in this response.\n'
    )
    links: Links5


class ListWebhooksResponse(BaseModel):
    data: List[WebhookResource] = Field(
        ..., description='The list of webhooks returned in this response.\n'
    )
    links: Links5


class Attributes2(BaseModel):
    amount: MoneyObject = Field(
        ...,
        description='The amount of this transaction in Australian dollars. For\ntransactions that were once `HELD` but are now `SETTLED`, refer to\nthe `holdInfo` field for the original `amount` the transaction was\n`HELD` at.\n',
    )
    cashback: CashbackObject = Field(
        ...,
        description='If all or part of this transaction was instantly reimbursed in the\nform of cashback, details of the reimbursement.\n',
    )
    createdAt: datetime = Field(
        ...,
        description='The date-time at which this transaction was first encountered.\n',
    )
    description: str = Field(
        ...,
        description='A short description for this transaction. Usually the merchant name\nfor purchases.\n',
    )
    foreignAmount: MoneyObject = Field(
        ...,
        description='The foreign currency amount of this transaction. This field will be\n`null` for domestic transactions. The amount was converted to the AUD\namount reflected in the `amount` of this transaction. Refer to the\n`holdInfo` field for the original `foreignAmount` the transaction was\n`HELD` at.\n',
    )
    holdInfo: HoldInfoObject = Field(
        ...,
        description='If this transaction is currently in the `HELD` status, or was ever in\nthe `HELD` status, the `amount` and `foreignAmount` of the\ntransaction while `HELD`.\n',
    )
    isCategorizable: bool = Field(
        ...,
        description='Boolean flag set to true on transactions that support the use of\ncategories.\n',
    )
    message: str = Field(
        ...,
        description='Attached message for this transaction, such as a payment message, or a\ntransfer note.\n',
    )
    rawText: str = Field(
        ...,
        description='The original, unprocessed text of the transaction. This is often not\na perfect indicator of the actual merchant, but it is useful for\nreconciliation purposes in some cases.\n',
    )
    roundUp: RoundUpObject = Field(
        ...,
        description='Details of how this transaction was rounded-up. If no Round Up was\napplied this field will be `null`.\n',
    )
    settledAt: datetime = Field(
        ...,
        description='The date-time at which this transaction settled. This field will be\n`null` for transactions that are currently in the `HELD` status.\n',
    )
    status: TransactionStatusEnum = Field(
        ...,
        description='The current processing status of this transaction, according to\nwhether or not this transaction has settled or is still held.\n',
    )


class TransactionResource(BaseModel):
    attributes: Attributes2
    id: str = Field(..., description='The unique identifier for this transaction.\n')
    links: Optional[Links11] = None
    relationships: Relationships3
    type: str = Field(..., description='The type of this resource: `transactions`')


class Attributes3(BaseModel):
    createdAt: datetime = Field(
        ..., description='The date-time at which this log entry was created.\n'
    )
    deliveryStatus: WebhookDeliveryStatusEnum = Field(
        ..., description='The success or failure status of this delivery attempt.\n'
    )
    request: Request = Field(
        ...,
        description='Information about the request that was sent to the webhook URL.\n',
    )
    response: Response = Field(
        ...,
        description='Information about the response that was received from the webhook URL.\n',
    )


class WebhookDeliveryLogResource(BaseModel):
    attributes: Attributes3
    id: str = Field(..., description='The unique identifier for this log entry.\n')
    relationships: Relationships4
    type: str = Field(
        ..., description='The type of this resource: `webhook-delivery-logs`'
    )


class Attributes4(BaseModel):
    createdAt: datetime = Field(
        ..., description='The date-time at which this event was generated.\n'
    )
    eventType: WebhookEventTypeEnum = Field(
        ...,
        description='The type of this event. This can be used to determine what action to\ntake in response to the event.\n',
    )


class WebhookEventResource(BaseModel):
    attributes: Attributes4
    id: str = Field(
        ...,
        description='The unique identifier for this event. This will remain constant across\ndelivery retries.\n',
    )
    relationships: Relationships5
    type: str = Field(..., description='The type of this resource: `webhook-events`')


class GetTransactionResponse(BaseModel):
    data: TransactionResource = Field(
        ..., description='The transaction returned in this response.\n'
    )


class ListTransactionsResponse(BaseModel):
    data: List[TransactionResource] = Field(
        ..., description='The list of transactions returned in this response.\n'
    )
    links: Links5


class ListWebhookDeliveryLogsResponse(BaseModel):
    data: List[WebhookDeliveryLogResource] = Field(
        ..., description='The list of delivery logs returned in this response.\n'
    )
    links: Links5


class WebhookEventCallback(BaseModel):
    data: WebhookEventResource = Field(
        ..., description='The webhook event data sent to the subscribed webhook.\n'
    )
